In [1]:
import numpy as np

from input import *

data = file("original.txt")
print(np.array(data))

[[[0.4  0.7  0.4  0.3 ]
  [0.3  0.27 0.4  0.7 ]
  [0.7  0.5  0.1  0.2 ]
  [0.6  0.5  0.9  0.4 ]
  [0.2  0.2  0.3  0.8 ]]

 [[0.6  0.5  0.8  0.2 ]
  [0.25 0.15 0.36 0.78]
  [0.8  0.9  0.   0.2 ]
  [0.7  0.6  0.96 0.45]
  [0.3  0.3  0.5  0.75]]

 [[0.3  0.9  0.1  0.1 ]
  [0.6  0.3  0.6  0.9 ]
  [0.65 0.25 0.4  0.5 ]
  [0.76 0.72 0.85 0.3 ]
  [0.35 0.3  0.45 0.87]]

 [[0.5  0.8  0.6  0.3 ]
  [0.1  0.1  0.8  0.2 ]
  [0.84 1.   0.5  0.  ]
  [0.65 0.57 0.8  0.35]
  [0.1  0.1  0.8  0.6 ]]

 [[0.7  0.65 0.2  0.8 ]
  [0.2  0.2  0.45 0.65]
  [0.5  0.7  0.4  0.6 ]
  [0.5  0.4  0.7  0.6 ]
  [0.8  0.7  0.2  0.3 ]]]


In [2]:
def si(a,b):
    mi = [min(a[i],b[i]) for i in range(4)]
    ma = [max(a[i],b[i]) for i in range(4)]
    out = sum(mi)/sum(ma)
    return out

def sim(a,b):
    temp = []
    for i in range(len(a)):
        temp.append(si(a[i],b[i]))
    out = np.mean(temp)
    return out

sim(data[1],data[2])


0.6407167127412767

In [3]:
def mm(a):
    out = []
    for i in range(len(a)):
        temp = []
        for j in range(len(a)):
            temp.append(round(sim(a[i],a[j]),3))
        out.append(temp)
    return out
mm(data)
#print(mm(data))

[[1.0, 0.762, 0.688, 0.632, 0.619],
 [0.762, 1.0, 0.641, 0.65, 0.591],
 [0.688, 0.641, 1.0, 0.562, 0.565],
 [0.632, 0.65, 0.562, 1.0, 0.512],
 [0.619, 0.591, 0.565, 0.512, 1.0]]

In [4]:
def cm(a):
    out = []
    for i in range(len(a)):
        temp = []
        for j in range(len(a)):
            t = [min(a[i][k],a[k][j]) for k in range(len(a))]
            temp.append(max(t))
        out.append(temp)
    return out

cm(mm(data))


[[1.0, 0.762, 0.688, 0.65, 0.619],
 [0.762, 1.0, 0.688, 0.65, 0.619],
 [0.688, 0.688, 1.0, 0.641, 0.619],
 [0.65, 0.65, 0.641, 1.0, 0.619],
 [0.619, 0.619, 0.619, 0.619, 1.0]]

In [5]:
def ecc(a):
    count = 0
    for i in range(len(a)):
        temp = []
        for j in range(len(a)):
            t = [min(a[i][k],a[k][j]) for k in range(len(a))]
            if max(t)<=a[i][j]:
                temp.append(1)
            else:
                temp.append(0)
        count+=sum(temp)
    return count==len(a)**2

print(ecc(cm(mm(data))))
print(ecc(cm(cm(mm(data)))))

False
True


In [6]:
def ecm(a):
    while ecc(a)==0:
        a = cm(a)
    return a

ecm(mm(data))

[[1.0, 0.762, 0.688, 0.65, 0.619],
 [0.762, 1.0, 0.688, 0.65, 0.619],
 [0.688, 0.688, 1.0, 0.65, 0.619],
 [0.65, 0.65, 0.65, 1.0, 0.619],
 [0.619, 0.619, 0.619, 0.619, 1.0]]

In [7]:
def cl(a):
    temp = []
    for i in range(len(a)):
        temp+= a[i]
    out = sorted(list(set(temp)))
    return out

print(cl(ecm(mm(data))))

[0.619, 0.65, 0.688, 0.762, 1.0]


In [8]:
def cum(a,ld):
    out = []
    for i in range(len(a)):
        temp = []
        for j in range(len(a)):
            if a[i][j] >= ld:
                temp.append(1)
            else:
                temp.append(0)
        out.append(temp)
    return out

cum(ecm(mm(data)),.688)

[[1, 1, 1, 0, 0],
 [1, 1, 1, 0, 0],
 [1, 1, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

In [9]:
test = [
    [1, 1, 0, 0, 0],[1, 1, 0, 0, 1],[0, 0, 1, 0, 0],[0, 0, 0, 1, 0],[0, 1, 0, 0, 1]
]
print(np.array(test))

[[1 1 0 0 0]
 [1 1 0 0 1]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 1 0 0 1]]


In [10]:
def label(a):
    out = [0]*len(a)
    gr = 1
    dele = []
    for i in range(len(a)):
        print(out)
        if i in dele:
            for j in range(len(a)):
                if (j>i) and (a[i][j] == 1):
                    print(i,j)
                    dele.append(j)
                    out[j] = out[i]
                    print(out,dele)
        if i not in dele:
            out[i] = gr
            for j in range(len(a)):
                if (j>i) and (a[i][j] == 1):
                    print(i,j)
                    dele.append(j)
                    out[j] = out[i]
                    print(out,dele)
            gr += 1
    return out
#label(test)
label(cum(ecm(mm(data)),.688))

[0, 0, 0, 0, 0]
0 1
[1, 1, 0, 0, 0] [1]
0 2
[1, 1, 1, 0, 0] [1, 2]
[1, 1, 1, 0, 0]
1 2
[1, 1, 1, 0, 0] [1, 2, 2]
[1, 1, 1, 0, 0]
[1, 1, 1, 0, 0]
[1, 1, 1, 2, 0]


[1, 1, 1, 2, 3]

In [11]:
def par(a):
    out = []
    for i in range(len(a)):
        temp = []
        for j in range(len(a)):
            if (j>=i) and (a[i][j] == 1):
                temp.append(j)
        out.append(temp)
    print(out)
    for i in range(len(out)):
        if len(out[i])==1:
            for j in range(len(out)):
                if out[i][0] in out[j] and len(out[i])!=1:
                    out.remove(j)
    return out

print(par(test))

[[0, 1], [1, 4], [2], [3], [4]]
[[0, 1], [1, 4], [2], [3], [4]]


In [12]:
def par(a):
    out = [0]*len(a)
    gr = 1
    for i in range(len(a)):
        print("thinh",i)
        if i == 0:
            out[i] = gr
            for j in range(len(a)):
                if a[i][j] == 1:
                    out[j] = gr
            print(out)
        else:
            if out[i]==0:
                out[i] = gr+1
                print(out)
                for j in range(len(a)):
                    print(i,j)
                    if j>i and a[i][j] == 1:
                        if out[j] == 0:
                            out[j] = gr+1
                        else:
                            out[j] = out[i]
    return out

par(test)

thinh 0
[1, 1, 0, 0, 0]
thinh 1
thinh 2
[1, 1, 2, 0, 0]
2 0
2 1
2 2
2 3
2 4
thinh 3
[1, 1, 2, 2, 0]
3 0
3 1
3 2
3 3
3 4
thinh 4
[1, 1, 2, 2, 2]
4 0
4 1
4 2
4 3
4 4


[1, 1, 2, 2, 2]