In [1]:
from evaluation import *
import matplotlib.pyplot as plt

In [2]:
data = file("data.txt")
print(np.array(data))

[[[0.97 0.9  0.1  0.1 ]
  [0.95 0.3  0.7  0.9 ]
  [0.99 1.   0.   0.1 ]
  ...
  [0.92 0.7  0.4  0.7 ]
  [0.93 0.7  0.4  0.7 ]
  [0.9  0.8  0.3  0.5 ]]

 [[0.8  0.8  0.4  0.7 ]
  [0.86 0.8  0.9  0.3 ]
  [0.79 0.9  0.1  0.5 ]
  ...
  [0.82 0.3  0.7  0.5 ]
  [0.86 0.3  0.7  0.5 ]
  [0.87 0.7  0.3  0.5 ]]

 [[0.97 0.9  0.2  0.1 ]
  [0.94 0.7  0.3  0.4 ]
  [0.9  0.9  0.1  0.1 ]
  ...
  [0.92 0.8  0.2  0.2 ]
  [0.95 0.8  0.2  0.2 ]
  [0.89 0.9  0.1  0.2 ]]

 ...

 [[0.83 1.   0.   0.  ]
  [0.79 1.   0.   0.  ]
  [0.71 1.   0.   0.  ]
  ...
  [0.84 1.   0.   0.  ]
  [0.83 1.   0.   0.  ]
  [0.94 1.   0.   0.  ]]

 [[0.92 0.8  0.2  0.6 ]
  [0.79 0.9  0.1  0.3 ]
  [0.83 0.3  0.8  0.8 ]
  ...
  [0.87 0.5  0.6  0.7 ]
  [0.92 0.8  0.2  0.2 ]
  [0.95 1.   0.   0.  ]]

 [[0.72 0.8  0.2  0.2 ]
  [0.67 0.9  0.1  0.1 ]
  [0.56 0.9  0.1  0.  ]
  ...
  [0.74 0.6  0.4  0.4 ]
  [0.75 0.7  0.3  0.2 ]
  [0.62 0.7  0.3  0.3 ]]]


In [3]:
sim = sim_mms(data[1],data[1])
print(sim)

1.0


In [4]:
memat = mmat(data,"s9")
print(np.array(memat))

[[1.    0.686 0.763 0.683 0.682 0.639 0.714 0.681 0.71  0.709 0.744 0.768
  0.67  0.711 0.744 0.714 0.77  0.624 0.705 0.662]
 [0.686 1.    0.665 0.711 0.583 0.602 0.738 0.639 0.748 0.675 0.675 0.682
  0.717 0.709 0.75  0.676 0.721 0.552 0.673 0.701]
 [0.763 0.665 1.    0.717 0.74  0.762 0.732 0.635 0.726 0.823 0.686 0.872
  0.728 0.825 0.71  0.787 0.774 0.762 0.787 0.756]
 [0.683 0.711 0.717 1.    0.668 0.609 0.732 0.653 0.754 0.695 0.704 0.723
  0.814 0.732 0.827 0.768 0.74  0.606 0.75  0.683]
 [0.682 0.583 0.74  0.668 1.    0.676 0.649 0.683 0.613 0.682 0.727 0.706
  0.666 0.706 0.656 0.678 0.69  0.717 0.694 0.665]
 [0.639 0.602 0.762 0.609 0.676 1.    0.643 0.617 0.62  0.751 0.602 0.771
  0.605 0.76  0.594 0.748 0.675 0.881 0.716 0.731]
 [0.714 0.738 0.732 0.732 0.649 0.643 1.    0.648 0.719 0.735 0.694 0.732
  0.746 0.772 0.764 0.695 0.744 0.603 0.743 0.723]
 [0.681 0.639 0.635 0.653 0.683 0.617 0.648 1.    0.612 0.656 0.779 0.674
  0.633 0.626 0.711 0.661 0.683 0.606 0.682 0.629]


In [5]:
comat = cmat(memat)
print(np.array(comat))

[[1.    0.744 0.77  0.744 0.74  0.768 0.744 0.744 0.767 0.768 0.744 0.768
  0.748 0.77  0.767 0.768 0.77  0.762 0.77  0.756]
 [0.744 1.    0.732 0.75  0.706 0.709 0.75  0.711 0.75  0.735 0.75  0.732
  0.75  0.743 0.75  0.741 0.75  0.709 0.75  0.723]
 [0.77  0.732 1.    0.768 0.74  0.771 0.772 0.71  0.767 0.823 0.744 0.872
  0.775 0.825 0.767 0.787 0.787 0.762 0.79  0.805]
 [0.744 0.75  0.768 1.    0.717 0.748 0.764 0.711 0.768 0.768 0.769 0.768
  0.814 0.775 0.827 0.768 0.767 0.747 0.762 0.734]
 [0.74  0.706 0.74  0.717 1.    0.74  0.732 0.727 0.726 0.74  0.727 0.74
  0.728 0.74  0.727 0.74  0.74  0.74  0.74  0.74 ]
 [0.768 0.709 0.771 0.748 0.74  1.    0.76  0.682 0.743 0.771 0.708 0.771
  0.76  0.771 0.729 0.771 0.768 0.881 0.771 0.76 ]
 [0.744 0.75  0.772 0.764 0.732 0.76  1.    0.711 0.764 0.772 0.764 0.772
  0.772 0.772 0.764 0.772 0.772 0.745 0.772 0.772]
 [0.744 0.711 0.71  0.711 0.727 0.682 0.711 1.    0.711 0.683 0.779 0.711
  0.711 0.711 0.769 0.711 0.741 0.683 0.711 0.688]
 

In [6]:
eqvmat = emat(memat)
print(np.array(eqvmat))

[[1.    0.75  0.77  0.77  0.74  0.77  0.77  0.769 0.768 0.77  0.769 0.77
  0.77  0.77  0.77  0.77  0.77  0.77  0.77  0.77 ]
 [0.75  1.    0.75  0.75  0.74  0.75  0.75  0.75  0.75  0.75  0.75  0.75
  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75 ]
 [0.77  0.75  1.    0.775 0.74  0.771 0.772 0.769 0.768 0.823 0.769 0.872
  0.775 0.825 0.775 0.787 0.79  0.771 0.79  0.805]
 [0.77  0.75  0.775 1.    0.74  0.771 0.772 0.769 0.768 0.775 0.769 0.775
  0.814 0.775 0.827 0.775 0.775 0.771 0.775 0.775]
 [0.74  0.74  0.74  0.74  1.    0.74  0.74  0.74  0.74  0.74  0.74  0.74
  0.74  0.74  0.74  0.74  0.74  0.74  0.74  0.74 ]
 [0.77  0.75  0.771 0.771 0.74  1.    0.771 0.769 0.768 0.771 0.769 0.771
  0.771 0.771 0.771 0.771 0.771 0.881 0.771 0.771]
 [0.77  0.75  0.772 0.772 0.74  0.771 1.    0.769 0.768 0.772 0.769 0.772
  0.772 0.772 0.772 0.772 0.772 0.771 0.772 0.772]
 [0.769 0.75  0.769 0.769 0.74  0.769 0.769 1.    0.768 0.769 0.779 0.769
  0.769 0.769 0.769 0.769 0.769 0.769 0.769 0.769]
 [0

In [7]:
print(lbd(eqvmat))
print(len(lbd(eqvmat)))
lctmat = lcmat(eqvmat,.338)
print(np.array(lctmat))

[0.74, 0.75, 0.768, 0.769, 0.77, 0.771, 0.772, 0.775, 0.779, 0.787, 0.79, 0.8, 0.805, 0.814, 0.823, 0.825, 0.827, 0.872, 0.881, 1.0]
20
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [8]:
clabel = label(lctmat)
print(clabel)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [9]:
clusters = cluster(clabel)
print(clusters)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]


In [10]:
#print(davies_bouldin_score(obj(data),clabel),silhouette_score(obj(data),clabel))

In [11]:
ld = list(lbd(eqvmat))
ld.remove(lbd(eqvmat)[0])
ld.remove(lbd(eqvmat)[len(lbd(eqvmat))-1])
x = [i for i in range(1,len(ld)+1)]
y = []
lb = []
for l in ld:
    lctmat_l = lcmat(eqvmat,l)
    clabel_l = label(lctmat_l)
    clusters_l = cluster(clabel_l)
    dbs = davies_bouldin_score(obj(data),clabel_l)
    ss = silhouette_score(obj(data),clabel_l)
    y.append(dbs)
    lb.append(len(clusters_l))
    print(l,len(clusters_l),round(dbs,3),round(ss,3))
#plt.plot(x,y)
#plt.xticks(x,lb)
#plt.show()

0.75 2 0.679 0.179
0.768 3 0.787 0.037
0.769 4 0.804 0.014
0.77 5 0.875 0.068
0.771 6 0.821 0.057
0.772 7 0.873 0.054
0.775 8 0.859 0.054
0.779 9 0.846 0.106
0.787 10 0.765 0.079
0.79 11 0.733 0.067
0.8 12 0.734 0.085
0.805 13 0.656 0.069
0.814 14 0.612 0.061
0.823 15 0.544 0.061
0.825 16 0.525 0.029
0.827 17 0.459 0.04
0.872 18 0.403 0.022
0.881 19 0.369 -0.001
