In [1]:
from original import *
from similarity import *

In [2]:
a = f("a.txt")
print(np.array(a))

[[0.9 0.7 0.5 0.6]
 [0.5 0.3 0.9 0.5]
 [0.2 0.1 0.4 0.7]
 [0.7 0.5 0.9 0.6]
 [0.7 0.3 0.9 0.1]]


In [3]:
ac = complement(a)
print(np.array(ac))

[[0.1 0.6 0.5 0.7]
 [0.5 0.5 0.1 0.3]
 [0.8 0.7 0.6 0.1]
 [0.3 0.6 0.1 0.5]
 [0.3 0.1 0.1 0.3]]


In [4]:
b = f("b.txt")
print(np.array(b))

[[0.7 0.3 0.4 0.3]
 [0.4 0.3 0.2 0.3]
 [0.5 0.1 0.8 0.8]
 [0.2 0.1 0.9 0.3]
 [0.8 0.5 0.8 0.8]]


In [5]:
bc = complement(b)
print(np.array(bc))

[[0.3 0.3 0.6 0.3]
 [0.6 0.3 0.8 0.3]
 [0.5 0.8 0.2 0.1]
 [0.8 0.3 0.1 0.1]
 [0.2 0.8 0.2 0.5]]


In [6]:
sub = issubset(a,b)
print(sub)

0


In [7]:
its = intersection(a,b)
print(np.array(its))

[[0.7 0.3 0.5 0.6]
 [0.4 0.3 0.9 0.5]
 [0.2 0.1 0.8 0.8]
 [0.2 0.1 0.9 0.6]
 [0.7 0.3 0.9 0.8]]


In [8]:
uno = union(a,b)
print(np.array(uno))

[[0.9 0.7 0.4 0.3]
 [0.5 0.3 0.2 0.3]
 [0.5 0.1 0.4 0.7]
 [0.7 0.5 0.9 0.3]
 [0.8 0.5 0.8 0.1]]


In [9]:
sdbs1 = round(sim_dbs(a,its),3)
sdbs2 = round(sim_dbs(b,uno),3)
sdbd1 = round(sim_dbd(a,its),3)
sdbd2 = round(sim_dbd(b,uno),3)
smmm1 = round(sim_mmm(a,its),3)
smmm2 = round(sim_mmm(b,uno),3)
srmm1 = round(sim_rmm(a,its),3)
srmm2 = round(sim_rmm(b,uno),3)
smms1 = round(sim_mms(a,its),3)
smms2 = round(sim_mms(b,uno),3)
smrms1 = round(sim_mrms(a,its),3)
smrms2 = round(sim_mrms(b,uno),3)
print(sdbs1,sdbs2)
print(sdbd1,sdbd2)
print(smmm1,smmm2)
print(srmm1,srmm2)
print(smms1,smms2)
print(smrms1,smrms2)

0.747 0.747
0.596 0.596
0.775 0.764
0.77 0.748
0.444 0.444
0.418 0.418


In [10]:
sdbs3 = round(sim_dbs(a,uno),3)
sdbs4 = round(sim_dbs(b,its),3)
sdbd3 = round(sim_dbd(a,uno),3)
sdbd4 = round(sim_dbd(b,its),3)
smmm3 = round(sim_mmm(a,uno),3)
smmm4 = round(sim_mmm(b,its),3)
srmm3 = round(sim_rmm(a,uno),3)
srmm4 = round(sim_rmm(b,its),3)
smms3 = round(sim_mms(a,uno),3)
smms4 = round(sim_mms(b,its),3)
smrms3 = round(sim_mrms(a,uno),3)
smrms4 = round(sim_mrms(b,its),3)
print(sdbs3,sdbs4)
print(sdbd3,sdbd4)
print(smmm3,smmm4)
print(srmm3,srmm4)
print(smms3,smms4)
print(smrms3,smrms4)

0.791 0.791
0.655 0.655
0.796 0.789
0.802 0.795
0.528 0.528
0.495 0.495


In [11]:
sdbs5 = round(sim_dbs(its,uno),3)
sdbs6 = round(sim_dbs(a,b),3)
sdbd5 = round(sim_dbd(its,uno),3)
sdbd6 = round(sim_dbd(a,b),3)
smmm5 = round(sim_mmm(its,uno),3)
smmm6 = round(sim_mmm(a,b),3)
srmm5 = round(sim_rmm(its,uno),3)
srmm6 = round(sim_rmm(a,b),3)
smms5 = round(sim_mms(its,uno),3)
smms6 = round(sim_mms(a,b),3)
smrms5 = round(sim_mrms(its,uno),3)
smrms6 = round(sim_mrms(a,b),3)
print(sdbs5,sdbs6)
print(sdbd5,sdbd6)
print(smmm5,smmm6)
print(srmm5,srmm6)
print(smms5,smms6)
print(smrms5,smrms5)

0.672 0.672
0.506 0.506
0.6 0.6
0.602 0.602
0.303 0.303
0.294 0.294


In [12]:
d1 = round(dp(1,a,b),3)
d2 = round(dp(2,a,b),3)
d7 = round(dp(7,a,b),3)
d8 = round(dvc(a,b),3)
print(d1,d2,d7,d8)

0.255 0.328 0.509 0.54


In [13]:
#ta = f("test_a.txt")
#tb = f("test_b.txt")

s11 = round(s1(a,its),3)
s12 = round(s1(b,uno),3)
s21 = round(s2(a,its),3)
s22 = round(s2(b,uno),3)
s31 = round(s3(a,its),3)
s32 = round(s3(b,uno),3)
s41 = round(s4(a,its),3)
s42 = round(s4(b,uno),3)
s51 = round(s5(a,its),3)
s52 = round(s5(b,uno),3)
s61 = round(s6(a,its),3)
s62 = round(s6(b,uno),3)
s71 = round(s7(a,its),3)
s72 = round(s7(b,uno),3)
s81 = round(s8(a,its),3)
s82 = round(s8(b,uno),3)
s91 = round(s9(a,its),3)
s92 = round(s9(b,uno),3)
print(s11,s12)
print(s21,s22)
print(s31,s32)
print(s41,s42)
print(s51,s52)
print(s61,s62)
print(s71,s72)
print(s81,s82)
print(s91,s92)

0.934 0.934
0.86 0.86
0.894 0.894
0.813 0.813
0.796 0.796
0.783 0.783
0.971 0.971
0.889 0.889
0.805 0.805


In [14]:
s13 = round(s1(a,uno),3)
s14 = round(s1(b,its),3)
s23 = round(s2(a,uno),3)
s24 = round(s2(b,its),3)
s33 = round(s3(a,uno),3)
s34 = round(s3(b,its),3)
s43 = round(s4(a,uno),3)
s44 = round(s4(b,its),3)
s53 = round(s5(a,uno),3)
s54 = round(s5(b,its),3)
s63 = round(s6(a,uno),3)
s64 = round(s6(b,its),3)
s73 = round(s7(a,uno),3)
s74 = round(s7(b,its),3)
s83 = round(s8(a,uno),3)
s84 = round(s8(b,its),3)
s93 = round(s9(a,uno),3)
s94 = round(s9(b,its),3)

print(s13,s14)
print(s23,s24)
print(s33,s34)
print(s43,s44)
print(s53,s54)
print(s63,s64)
print(s73,s74)
print(s83,s84)
print(s93,s94)

0.955 0.955
0.885 0.885
0.914 0.914
0.845 0.845
0.83 0.83
0.821 0.821
0.98 0.98
0.909 0.909
0.836 0.836


In [15]:
s15 = round(s1(its,uno),3)
s16 = round(s1(a,b),3)
s25 = round(s2(its,uno),3)
s26 = round(s2(a,b),3)
s35 = round(s3(its,uno),3)
s36 = round(s3(a,b),3)
s45 = round(s4(its,uno),3)
s46 = round(s4(a,b),3)
s55 = round(s5(its,uno),3)
s56 = round(s5(a,b),3)
s65 = round(s6(its,uno),3)
s66 = round(s6(a,b),3)
s75 = round(s7(its,uno),3)
s76 = round(s7(a,b),3)
s85 = round(s8(its,uno),3)
s86 = round(s8(a,b),3)
s95 = round(s9(its,uno),3)
s96 = round(s9(a,b),3)

print(s15,s16)
print(s25,s26)
print(s35,s36)
print(s45,s46)
print(s55,s56)
print(s65,s66)
print(s75,s76)
print(s85,s86)
print(s95,s96)

0.889 0.889
0.745 0.745
0.803 0.803
0.673 0.673
0.645 0.645
0.611 0.611
0.92 0.92
0.797 0.797
0.663 0.663
