In [91]:
from evaluation import *

In [92]:
data = file("original.txt")
print(np.array(data))

[[[0.4  0.7  0.4  0.3 ]
  [0.3  0.27 0.4  0.7 ]
  [0.7  0.5  0.1  0.2 ]
  [0.6  0.5  0.9  0.4 ]
  [0.2  0.2  0.3  0.8 ]]

 [[0.6  0.5  0.8  0.2 ]
  [0.25 0.15 0.36 0.78]
  [0.8  0.9  0.   0.2 ]
  [0.7  0.6  0.96 0.45]
  [0.3  0.3  0.5  0.75]]

 [[0.3  0.9  0.1  0.1 ]
  [0.6  0.3  0.6  0.9 ]
  [0.65 0.25 0.4  0.5 ]
  [0.76 0.72 0.85 0.3 ]
  [0.35 0.3  0.45 0.87]]

 [[0.5  0.8  0.6  0.3 ]
  [0.1  0.1  0.8  0.2 ]
  [0.84 1.   0.5  0.  ]
  [0.65 0.57 0.8  0.35]
  [0.1  0.1  0.8  0.6 ]]

 [[0.7  0.65 0.2  0.8 ]
  [0.2  0.2  0.45 0.65]
  [0.5  0.7  0.4  0.6 ]
  [0.5  0.4  0.7  0.6 ]
  [0.8  0.7  0.2  0.3 ]]]


In [93]:
sim = sim_mms(data[1],data[1])
print(sim)

1.0


In [94]:
memat = mmat(data,"dvc1")
print(np.array(memat))

[[1.    0.756 0.746 0.64  0.64 ]
 [0.756 1.    0.606 0.632 0.622]
 [0.746 0.606 1.    0.51  0.512]
 [0.64  0.632 0.51  1.    0.5  ]
 [0.64  0.622 0.512 0.5   1.   ]]


In [95]:
comat = cmat(memat)
print(np.array(comat))

[[1.    0.756 0.746 0.64  0.64 ]
 [0.756 1.    0.746 0.64  0.64 ]
 [0.746 0.746 1.    0.64  0.64 ]
 [0.64  0.64  0.64  1.    0.64 ]
 [0.64  0.64  0.64  0.64  1.   ]]


In [96]:
eqvmat = emat(memat)
print(np.array(eqvmat))

[[1.    0.756 0.746 0.64  0.64 ]
 [0.756 1.    0.746 0.64  0.64 ]
 [0.746 0.746 1.    0.64  0.64 ]
 [0.64  0.64  0.64  1.    0.64 ]
 [0.64  0.64  0.64  0.64  1.   ]]


In [97]:
print(lbd(eqvmat))
lctmat = lcmat(eqvmat,0.75)
print(np.array(lctmat))

[0.64, 0.746, 0.756, 1.0]
[[1 1 0 0 0]
 [1 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [98]:
clabel = label(lctmat)
print(clabel)

[0, 0, 1, 2, 3]


In [99]:
clusters = cluster(clabel)
print(clusters)

[[0, 1], [2], [3], [4]]


In [100]:
print(davies_bouldin_score(obj(data),clabel),silhouette_score(obj(data),clabel))

0.3307002439918144 0.09635353409377896
